version: "3.0"
services:
   storage:
     image: sonatype/nexus3
     container_name: nxs
     
     ports:
     - "8081:8081"
     volumes:
     - ./nexus.properties:/nexus-data/etc/nexus.properties
     - ./startfolder:/startfolder

   proxy:
      image: state
      container_name: ngx
      restart: unless-stopped
      tty: true
    
      ports:
      - "443:443"
      - "8080:8080"
      volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
